/*
Script DB
*/

CREATE DATABASE loymarkdb;

DROP TABLE IF EXISTS public."Usuarios";

CREATE TABLE IF NOT EXISTS public."Usuarios"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "Apellido" text COLLATE pg_catalog."default" NOT NULL,
    "CorreoElectronico" text COLLATE pg_catalog."default" NOT NULL,
    "FechaDeNacimiento" timestamp with time zone NOT NULL,
    "NumeroDeTelefono" bigint NOT NULL,
    "PaisDeResidencia" text COLLATE pg_catalog."default" NOT NULL,
    "Contacto" boolean NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS public."Actividades";

CREATE TABLE IF NOT EXISTS public."Actividades"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FechaDeCreacion" timestamp with time zone NOT NULL,
    "IdUsuario" integer NOT NULL,
    "Actividad" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Actividades" PRIMARY KEY ("Id")
);


INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Santiago', 'Orellano', 'santiorellano7@gmail.com', '18-04-1997', 3534177575, 'ARG', true);

INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Cristian', 'Ronaldo', 'cronaldo7@gmail.com', '18-01-1997', 3534787983, 'ARG', true);

INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Lionel', 'Messi', 'lmessi10@gmail.com', '24-06-1987', 3534789451, 'BRA', true);

INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Juan', 'Rodriguez', 'jrodriguez@gmail.com', '01-01-1995', 3534787989, 'ARG', true);

INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Gonzalo', 'Oliver', 'goliver@gmail.com', '27-02-1997', 3535789123, 'ARG', true);

INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Roman', 'Riquelme', 'jrriquelme@gmail.com', '10-10-1980', 3534101010, 'ARG', true);

INSERT INTO public."Usuarios"("Nombre", "Apellido", "CorreoElectronico", "FechaDeNacimiento", "NumeroDeTelefono", "PaisDeResidencia", "Contacto")
    VALUES ('Neymar', 'Jr', 'neymarjr@gmail.com', '05-02-1992', 3534112151, 'BRA', true);